# Exercise 01

In [1]:
# libraries

import numpy as np
import pandas as pd

In [2]:
# What's the version of NumPy that you installed?
np.__version__

'1.21.2'

In [3]:
# What's the version of Pandas?
pd.__version__

'1.3.3'

In [5]:
# Download the dataset from the following URL
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv -O ./datasets/Ex01/data.csv

--2021-09-13 13:10:26--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: ‘./datasets/data.csv’

./datasets/data.csv 100%[===================>]   1.41M  5.82MB/s    in 0.2s    

2021-09-13 13:10:27 (5.82 MB/s) - ‘./datasets/data.csv’ saved [1475504/1475504]



In [6]:
# Read the dataset using pandas
data = pd.read_csv("./datasets/Ex01/data.csv")
data

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

In [7]:
# let's list all the columns
data.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

In [13]:
# What's the average price of BMW cars in the dataset?
data[data.Make == 'BMW'].MSRP.mean().round(2)

61546.76

In [14]:
# Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP?
data[data.Year >= 2015]['Engine HP'].isnull().sum()

51

In [15]:
# Calculate the average "Engine HP" in the dataset.
data['Engine HP'].mean().round(2)

249.39

In [16]:
# Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.
data['Engine HP'].fillna(value = data['Engine HP'].mean(), inplace = True)

In [17]:
# calcualte the average of "Engine HP" again
data['Engine HP'].mean().round(2)

249.39

In [20]:
# Select all the "Rolls-Royce" cars from the dataset.
# Select only columns "Engine HP", "Engine Cylinders", "highway MPG".
# Now drop all duplicated rows using drop_duplicates method
# Get the underlying NumPy array. Let's call it X
X = np.array(data[data.Make == 'Rolls-Royce'][['Engine HP', 'Engine Cylinders', 'highway MPG']].drop_duplicates())
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [21]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XTX = (X.T).dot(X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [24]:
# Invert XTX
# What's the sum of all the elements of the result?
np.linalg.inv(XTX).sum().round(4)

0.0322

In [25]:
# Create an array y with values [1000, 1100, 900, 1200, 1000, 850, 1300].
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

In [27]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w
w = (np.linalg.inv(XTX).dot(X.T)).dot(y)
w

array([ 0.19989598, 31.02612262, 31.65378877])

In [28]:
# What's the value of the first element of w?
w[0]

0.19989598183188972